### ISSUE TITLE
mkdir build

### ISSUE THREAD

**Issue by trosh** [luke8086/boot2c#1]
On a clean clone, there is no `build` folder.

Therefore, `make` results in:

```
as -march=i386 --32 boot.s -o build/boot.elf
Assembler messages:
Fatal error: can't create build/boot.elf: No such file or directory
```

**Comment by luke8086** [comment]
Good catch, thanks! Fixed in ab75bcb20e6557f0ea32e6e79bf2cf4c4e332b61
